version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 782546527822.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo Login completed on `date`
  build:
    commands:
      - echo Build started on `date`
      # Build the Docker images
      - echo Building the production Docker image...
      - docker-compose --file=docker-compose.yml up --build -d rooms
      - echo Build completed on `date`
  post_build:
    commands:
      # Take these images and push them to ECR
      - echo Pushing the Docker images...
      - docker tag src_rooms:latest 782546527822.dkr.ecr.$AWS_REGION.amazonaws.com/hablaqui-$ENTORNO_CLOUD:latest
      - docker push 782546527822.dkr.ecr.$AWS_REGION.amazonaws.com/hablaqui-$ENTORNO_CLOUD:latest
      - docker tag 782546527822.dkr.ecr.$AWS_REGION.amazonaws.com/hablaqui-$ENTORNO_CLOUD:latest 782546527822.dkr.ecr.$AWS_REGION.amazonaws.com/hablaqui-$ENTORNO_CLOUD:$CODEBUILD_BUILD_NUMBER
      - docker push 782546527822.dkr.ecr.$AWS_REGION.amazonaws.com/hablaqui-$ENTORNO_CLOUD:$CODEBUILD_BUILD_NUMBER
      - echo Pushing completed on `date`

artifacts:
  files:
    - images/$ENTORNO_CLOUD-image.json