version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 782546527822.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo Login completed on `date`
      - echo Extaer las variables de entorno
      - export TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID
      - export TWILIO_API_KEY_SECRET=$TWILIO_API_KEY_SECRET
      - export TWILIO_API_KEY_SID=$TWILIO_API_KEY_SID
      - export TWILIO_CONVERSATIONS_SERVICE_SID=$TWILIO_CONVERSATIONS_SERVICE_SID
      - export TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN
      - export REACT_APP_FIREBASE_API_KEY=$REACT_APP_FIREBASE_API_KEY
      - export REACT_APP_FIREBASE_AUTH_DOMAIN=$REACT_APP_FIREBASE_AUTH_DOMAIN
      - export REACT_APP_FIREBASE_DATABASE_URL=$REACT_APP_FIREBASE_DATABASE_URL
      - export REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$REACT_APP_FIREBASE_MESSAGING_SENDER_ID
      - echo Variables de entorno extraidas
  build:
    commands:
      - echo Build started on `date`
      # Build the Docker images
      - echo Building the production Docker image...
      - docker-compose --file=docker-compose.yml up --build -d rooms
      - echo Build completed on `date`
  post_build:
    commands:
      # Take these images and push them to ECR
      - echo Pushing the Docker images...
      - docker tag src_rooms:latest 782546527822.dkr.ecr.$AWS_REGION.amazonaws.com/hablaqui-$ENTORNO_CLOUD:latest
      - docker push 782546527822.dkr.ecr.$AWS_REGION.amazonaws.com/hablaqui-$ENTORNO_CLOUD:latest
      - docker tag 782546527822.dkr.ecr.$AWS_REGION.amazonaws.com/hablaqui-$ENTORNO_CLOUD:latest 782546527822.dkr.ecr.$AWS_REGION.amazonaws.com/hablaqui-$ENTORNO_CLOUD:$CODEBUILD_BUILD_NUMBER
      - docker push 782546527822.dkr.ecr.$AWS_REGION.amazonaws.com/hablaqui-$ENTORNO_CLOUD:$CODEBUILD_BUILD_NUMBER
      - echo Pushing completed on `date`

artifacts:
  files:
    - images/$ENTORNO_CLOUD-image.json