steps:
  - name: node:12
    entrypoint: npm
    args: ['install']
    id: 'install'
    waitFor: ['-']
  - name: node:12
    entrypoint: npm
    args: ['run', 'create-env']
    env:
      - 'TWILIO_ACCOUNT_SID=${_TWILIO_ACCOUNT_SID}'
      - 'TWILIO_API_KEY_SECRET=${_TWILIO_API_KEY_SECRET}'
      - 'TWILIO_API_KEY_SID=${_TWILIO_API_KEY_SID}'
      - 'TWILIO_CONVERSATIONS_SERVICE_SID=${_TWILIO_CONVERSATIONS_SERVICE_SID}'
      - 'TWILIO_AUTH_TOKEN=${_TWILIO_AUTH_TOKEN}'
      - 'REACT_APP_FIREBASE_API_KEY=${_REACT_APP_FIREBASE_API_KEY}'
      - 'REACT_APP_FIREBASE_AUTH_DOMAIN=${_REACT_APP_FIREBASE_AUTH_DOMAIN}'
      - 'REACT_APP_FIREBASE_DATABASE_URL=${_REACT_APP_FIREBASE_DATABASE_URL}'
      - 'REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${_REACT_APP_FIREBASE_MESSAGING_SENDER_ID}'
      - 'REACT_APP_FIREBASE_STORAGE_BUCKET=${_REACT_APP_FIREBASE_STORAGE_BUCKET}'
      - 'REACT_APP_SET_AUTH=${_REACT_APP_SET_AUTH}'

    id: 'envvars'
    waitFor: ['install']
  - name: node:12
    entrypoint: npm
    args: ['run', 'build']
    id: 'build'
    waitFor: ['envvars']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
    id: 'deploy'
    waitFor: ['envvars', 'install', 'build']

timeout: '2600s'
