runtime: nodejs14
instance_class: F1
automatic_scaling:
    max_instances: 3
 

entrypoint: npm run server

# env_variables:
#   REACT_APP_SET_AUTH: 'firebase'

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
